tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: "on-partial"
    before: |
      # Change to workspace directory
      cd /workspace
      # Download and install AWS CLI
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install